# Generated by Django 2.2 on 2019-12-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('t_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('t_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('i_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('expire', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=40)),
                ('i_level', models.IntegerField(default=0)),
                ('i_tag', models.ForeignKey(on_delete='CASCADE', to='listdata.Tag')),
            ],
        ),
    ]
